PRESETS = {
    "fashion": {
        "palette": ["#111111", "#e8dfd2", "#9c7a4d", "#ffffff", "#d4af37"],
        "headline_examples": ["ELEGANT EVERYDAY STYLE", "NEW SEASON COLLECTION", "LUXURY IN EVERY DETAIL"],
        "cta": "SHOP THE LOOK",
        "layout": "left_copy_right_hero",
        "badge": "NEW COLLECTION",
        "bullets": ["Premium finish", "Elegant gold detail", "Everyday luxury"],
    },
    "beverage": {
        "palette": ["#0b0b0b", "#d71920", "#ffffff", "#f5f5f5", "#ffcc00"],
        "headline_examples": ["REFRESH YOUR MOMENT", "TASTE THE ENERGY", "CHILL. SIP. ENJOY."],
        "cta": "DISCOVER MORE",
        "layout": "hero_center_bold_brand",
        "badge": "LIMITED CAMPAIGN",
        "bullets": ["Bold taste", "Fresh energy", "Serve chilled"],
    },
    "sports": {
        "palette": ["#111111", "#f97316", "#ffffff", "#ffd4ad", "#222222"],
        "headline_examples": ["MARATHON", "RUN FOR A GOOD CAUSE", "JOIN THE CHALLENGE"],
        "cta": "REGISTER NOW",
        "layout": "event_poster",
        "badge": "ANNUAL EVENT",
        "bullets": ["Date schedule", "Event details", "Registration info"],
    },
    "nature": {
        "palette": ["#243b2f", "#f5f0df", "#2f5d3a", "#8b6f47", "#ffffff"],
        "headline_examples": ["DISCOVER HIDDEN NATURE", "THE SMALL WORLD BELOW", "NATURE UP CLOSE"],
        "cta": "LEARN MORE",
        "layout": "macro_educational",
        "badge": "NATURE SERIES",
        "bullets": ["Macro detail", "Natural habitat", "Educational visual"],
    },
    "food": {
        "palette": ["#2b120c", "#fff1df", "#d9480f", "#ffffff", "#ffd166"],
        "headline_examples": ["FRESH FLAVOR AWAITS", "TASTE THE MOMENT", "MADE TO CRAVE"],
        "cta": "ORDER NOW",
        "layout": "food_campaign",
        "badge": "SPECIAL MENU",
        "bullets": ["Fresh ingredients", "Rich flavor", "Made daily"],
    },
    "portrait": {
        "palette": ["#111827", "#f3f4f6", "#8b5cf6", "#ffffff", "#c4b5fd"],
        "headline_examples": ["NEW STORY. NEW LOOK.", "EDITORIAL PORTRAIT", "STYLE IN FOCUS"],
        "cta": "VIEW MORE",
        "layout": "editorial_portrait",
        "badge": "EDITORIAL",
        "bullets": ["Identity preserved", "Modern styling", "Client ready"],
    },
    "general": {
        "palette": ["#111827", "#e5e7eb", "#38bdf8", "#ffffff", "#94a3b8"],
        "headline_examples": ["FEATURE HIGHLIGHT", "NEW VISUAL STORY", "DISCOVER MORE"],
        "cta": "LEARN MORE",
        "layout": "balanced_modern",
        "badge": "NEW CAMPAIGN",
        "bullets": ["Clean design", "Source preserved", "Ready to share"],
    },
}
